#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pip"]
# ///
"""Vendor the pure-Python wheels webblinka installs into Pyodide.

Run with:  uv run scripts/fetch_wheels.py

Everything here must be a py3-none-any wheel -- Pyodide can only load pure
Python from a plain wheel, and passing --abi none --platform any makes pip fail
loudly rather than silently grabbing a native build for the host.

The dependency closure is pinned explicitly rather than resolved, because pip
evaluates environment markers against the *host* (sysv_ipc is a linux-only dep
of adafruit-blinka and is source-only, so a resolved download would break in
Linux CI while working on a Mac). Pyodide reports sys_platform == "emscripten",
so none of the platform-gated deps apply there anyway.

micropip installs this set with deps=False, so the list below has to be the
complete closure. To re-derive it after a version bump:

    uv run --with pip pip download --only-binary :all: adafruit-blinka -d /tmp/x
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

# Pyodide 314.x runs CPython 3.14.
PYTHON_VERSION = "3.14"

# The closure micropip installs. Comments say why each one is here.
REQUIREMENTS = [
    "adafruit-blinka==9.2.0",  # board / busio / digitalio / analogio
    "Adafruit-PlatformDetect==3.89.1",  # chip + board detection (reads BLINKA_MCP2221)
    "Adafruit-PureIO==1.1.11",  # hard dep of blinka; unused on the MCP2221 path
    "adafruit-circuitpython-typing==1.12.3",  # hard dep of blinka
    "adafruit-circuitpython-busdevice==5.2.17",  # I2CDevice, used by most drivers
    "adafruit-circuitpython-requests==4.1.17",  # dep of circuitpython-typing
    "adafruit-circuitpython-connectionmanager==3.1.8",  # dep of circuitpython-requests
    "binho-host-adapter==0.1.6",  # hard dep of blinka
    "pyftdi==0.57.2",  # hard dep of blinka
    "pyusb==1.3.1",  # dep of pyftdi
    "pyserial==3.5",  # dep of pyftdi and binho-host-adapter
    # Device drivers backing the built-in panels.
    "adafruit-circuitpython-gps==3.11.9",  # PA1010D and friends
    "adafruit-circuitpython-ahtx0==1.0.30",  # AHT10/AHT20/AHT21/DHT20
    "adafruit-circuitpython-as7341==1.2.27",  # 11-channel spectral sensor
    "adafruit-circuitpython-sht4x==1.0.27",  # SHT40/41/43/45
    "adafruit-circuitpython-hdc302x==1.0.10",  # HDC3020/3021/3022
    "adafruit-circuitpython-as5600==1.0.3",  # magnetic rotary encoder
    "adafruit-circuitpython-tsl2591==1.4.8",  # high-dynamic-range light sensor
    "adafruit-circuitpython-register==1.10.4",  # dep of as7341
    "adafruit-circuitpython-apds9960==3.1.19",  # APDS9960 proximity/gesture/color
]

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "public" / "wheels"


def main() -> int:
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)

    cmd = [
        sys.executable,
        "-m",
        "pip",
        "download",
        "--no-deps",
        "--only-binary",
        ":all:",
        "--implementation",
        "py",
        "--python-version",
        PYTHON_VERSION,
        "--abi",
        "none",
        "--platform",
        "any",
        "--dest",
        str(OUT),
        *REQUIREMENTS,
    ]
    print(" ".join(cmd))
    subprocess.run(cmd, check=True)

    files = sorted(p.name for p in OUT.glob("*.whl"))
    if len(files) != len(REQUIREMENTS):
        print(
            f"expected {len(REQUIREMENTS)} wheels, got {len(files)}: {files}",
            file=sys.stderr,
        )
        return 1

    manifest = {
        "_comment": "Generated by scripts/fetch_wheels.py -- do not edit by hand.",
        "pythonVersion": PYTHON_VERSION,
        "requirements": REQUIREMENTS,
        "files": files,
    }
    (OUT / "wheels.json").write_text(json.dumps(manifest, indent=2) + "\n")

    total = sum(p.stat().st_size for p in OUT.glob("*.whl"))
    print(f"\nvendored {len(files)} wheels, {total / 1024:.0f} KiB total -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
